local mod = get_mod("ForTheEmperor")

return {
	name = mod:localize("mod_title"),
	description = mod:localize("mod_description"),
	is_togglable = true,
	options = {
		widgets = {
			{
				setting_id = "options",
				type = "group",
				sub_widgets = {
					{
						setting_id = "disable_dibs",
						tooltip = "disable_dibs_desc",
						type = "checkbox",
						default_value = true,
					},
					{
						setting_id = "ignore_help",
						tooltip = "ignore_help_desc",
						type = "checkbox",
						default_value = false,
					},
				},
			},
			{
				setting_id = "keybinds",
				type = "group",
				sub_widgets = {
					{
						setting_id = "keybind_emperor",
						type = "keybind",
						keybind_trigger = "pressed",
						keybind_type = "function_call",
						function_name = "keybind_emperor",
						default_value = {},
					},
					{
						setting_id = "keybind_no",
						type = "keybind",
						keybind_trigger = "pressed",
						keybind_type = "function_call",
						function_name = "keybind_no",
						default_value = {},
					},
					{
						setting_id = "keybind_yes",
						type = "keybind",
						keybind_trigger = "pressed",
						keybind_type = "function_call",
						function_name = "keybind_yes",
						default_value = {},
					},
					{
						setting_id = "keybind_thanks",
						type = "keybind",
						keybind_trigger = "pressed",
						keybind_type = "function_call",
						function_name = "keybind_thanks",
						default_value = {},
					},
					{
						setting_id = "keybind_ammo",
						type = "keybind",
						keybind_trigger = "pressed",
						keybind_type = "function_call",
						function_name = "keybind_ammo",
						default_value = {},
					},
					{
						setting_id = "keybind_health",
						type = "keybind",
						keybind_trigger = "pressed",
						keybind_type = "function_call",
						function_name = "keybind_health",
						default_value = {},
					},
					{
						setting_id = "keybind_help",
						type = "keybind",
						keybind_trigger = "pressed",
						keybind_type = "function_call",
						function_name = "keybind_help",
						default_value = {},
					},
					{
						setting_id = "keybind_attention",
						type = "keybind",
						keybind_trigger = "pressed",
						keybind_type = "function_call",
						function_name = "keybind_attention",
						default_value = {},
					},
					{
						setting_id = "keybind_location",
						type = "keybind",
						keybind_trigger = "pressed",
						keybind_type = "function_call",
						function_name = "keybind_location",
						default_value = {},
					},
					{
						setting_id = "keybind_enemy",
						type = "keybind",
						keybind_trigger = "pressed",
						keybind_type = "function_call",
						function_name = "keybind_enemy",
						default_value = {},
					},
				},
			},
		},
	},
}
